import { Inter } from "next/font/google";
import { Space_Mono } from "next/font/google";
import { Inconsolata } from "next/font/google";

import "@/app/ui/global.css";

const inter = Inter({ subsets: ["latin"] });
const spaceMono = Space_Mono({ subsets: ["latin"], weight: '400' });
const inconsolata = Inconsolata({ subsets: ["latin"], weight: '400' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inconsolata.className}>{children}</body>
    </html>
  );
}
